// <auto-generated />
namespace NetCommunitySolution.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Create_RewardPointHistory_Scripts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_RewardPointHistory_Scripts));
        
        string IMigrationMetadata.Id
        {
            get { return "201712180725439_Create_RewardPointHistory_Scripts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
